DOMAIN = "stpt_transit"
CONF_STATIONS = "stations"
CONF_STOP_ID = "stop_id"
CONF_NAME = "name"
CONF_LINES = "lines"
CONF_REFRESH_INTERVAL = "refresh_interval"
DEFAULT_NAME = "STPT Station"
DEFAULT_REFRESH_INTERVAL = 10
ATTRIBUTION = "Data from STPT (Societatea de Transport Public Timi\u0219oara)"
LIVE_API_URL = "https://live.stpt.ro/proxy-smtt-cache.php"
ALERTS_API_URL = "https://live.stpt.ro/proxy-alerts.php"
VEHICLES_API_URL = "https://live.stpt.ro/gtfs-vehicles.php"
STATIONS_MAP_FILE = "stations_map.json"
UPDATE_INTERVAL = 15
